// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineOrder.Db;

#nullable disable

namespace OnlineOrder.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250503060520_UpdateOrderProduct")]
    partial class UpdateOrderProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineOrder.Db.Models.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("created")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Orderid")
                        .HasColumnType("uuid");

                    b.Property<int>("QTY")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Orderid");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = new Guid("68e896f8-c272-4b92-b52d-10d83e6452a2"),
                            QTY = 0
                        },
                        new
                        {
                            id = new Guid("86e210d8-3e55-4887-a957-55fa04bc7fc0"),
                            QTY = 0
                        },
                        new
                        {
                            id = new Guid("734b060e-7385-4c35-bfad-2187c5d8fd6c"),
                            QTY = 0
                        },
                        new
                        {
                            id = new Guid("5a6429bd-cc54-4252-a6ea-e370fcdada15"),
                            QTY = 0
                        });
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.OrderProduct", b =>
                {
                    b.HasOne("OnlineOrder.Db.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineOrder.Db.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.Product", b =>
                {
                    b.HasOne("OnlineOrder.Db.Models.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("Orderid");
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("OnlineOrder.Db.Models.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
